version: '2'

volumes:
  nextcloud:
  db:

services:
  db:
    image: mariadb:10.6.0
    restart: always
    #command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW 
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW --innodb-read-only-compressed=OFF
    volumes:
      - db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=mysql-password
      - MYSQL_PASSWORD=mysql-password
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud

  app:
    image: nextcloud
    restart: always
    ports:
      - 127.0.0.1:8080:80
    links:
      - db
    volumes:
      - nextcloud:/var/www/html
      - /data/files:/var/www/html/data
    environment:
      - MYSQL_PASSWORD=mysql-password
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - MYSQL_HOST=db
      - OVERWRITEHOST=nas.local
      - OVERWRITEPROTOCOL=https
