version: "3"

# More info at https://github.com/pi-hole/docker-pi-hole/ and https://docs.pi-hole.net/
services:
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    ports:
      - "53:53/tcp"
      - "53:53/udp"
#      - "67:67/udp"
      - "81:80/tcp"
      - "444:443/tcp"
    environment:
      TZ: 'Europe/Stockholm'
      WEBPASSWORD: 'pi-hole-admin'
    # Volumes store your data between container upgrades
    volumes:
      - '/data/system/apps/pihole/etc-pihole/:/etc/pihole/'
      - '/data/system/apps/pihole/etc-dnsmasq.d/:/etc/dnsmasq.d/'
    # Recommended but not required (DHCP needs NET_ADMIN)
    #   https://github.com/pi-hole/docker-pi-hole#note-on-capabilities
    cap_add:
      - NET_ADMIN
    restart: unless-stopped

